import type { ServicePreset } from "../core/types.js";

/**
 * Built-in service presets for common analytics, marketing, media, payments, and security tools.
 * Compliant with AEPD / GDPR / LSSI standards with pre-configured cookie names, storage keys,
 * providers, and default categories.
 */
export const SERVICE_PRESETS: Record<string, ServicePreset> = {
  // --- ANALYTICS ---
  ga4: {
    id: "ga4",
    category: "analytics",
    label: "Google Analytics 4",
    provider: "Google LLC",
    description: "Medición de visitas, páginas vistas, eventos y comportamiento de navegación del usuario.",
    policyUrl: "https://policies.google.com/privacy",
    cookies: [
      { name: "_ga", duration: "2 años", purpose: "Distinguir a los usuarios únicos en el sitio web." },
      { name: "_ga_*", duration: "2 años", purpose: "Mantener el estado de la sesión de Google Analytics 4." },
      { name: "_gid", duration: "24 horas", purpose: "Distinguir a los usuarios durante un único día." },
      { name: "_gat*", duration: "1 minuto", purpose: "Limitar el porcentaje de solicitudes a Google Analytics." },
    ],
    storageKeys: ["_ga_*", "google_analytics_*"],
    localStorage: ["_ga_*", "google_analytics_*"],
  },
  google_analytics: {
    id: "google_analytics",
    category: "analytics",
    label: "Google Analytics (Universal / GA4)",
    provider: "Google LLC",
    description: "Medición de visitas y estadísticas anónimas de tráfico web.",
    policyUrl: "https://policies.google.com/privacy",
    cookies: [
      { name: "_ga", duration: "2 años", purpose: "Distinguir usuarios." },
      { name: "_ga_*", duration: "2 años", purpose: "Estado de la sesión GA4." },
      { name: "_gid", duration: "24 horas", purpose: "Identificador diario." },
    ],
    storageKeys: ["_ga_*"],
  },
  posthog: {
    id: "posthog",
    category: "analytics",
    label: "PostHog Analytics",
    provider: "PostHog, Inc.",
    description: "Analítica de producto, registro de sesiones, mapas de ruta y embudos de interacción.",
    policyUrl: "https://posthog.com/privacy",
    cookies: [
      { name: "ph_*_posthog", duration: "1 año", purpose: "Persistencia de usuario e identificación de sesiones en PostHog." },
    ],
    storageKeys: ["ph_*_posthog"],
    localStorage: ["ph_*_posthog"],
    sessionStorage: ["ph_*_posthog"],
  },
  hotjar: {
    id: "hotjar",
    category: "analytics",
    label: "Hotjar Heatmaps & Feedback",
    provider: "Hotjar Ltd.",
    description: "Mapas de calor de clics, desplazamientos, grabaciones de comportamiento y encuestas.",
    policyUrl: "https://www.hotjar.com/legal/policies/privacy/",
    cookies: [
      { name: "_hjSession*", duration: "30 minutos", purpose: "Mantener los datos de la sesión actual del usuario en Hotjar." },
      { name: "_hjSessionUser*", duration: "1 año", purpose: "Mantener el ID de usuario anónimo en el navegador." },
      { name: "_hjIncludedIn*", duration: "Sesión", purpose: "Determinar si el usuario está incluido en el muestreo de datos." },
      { name: "_hjAbsoluteCanvasUrl", duration: "Sesión", purpose: "Almacenar la URL canónica de visualización." },
      { name: "_hjTLDTest", duration: "Sesión", purpose: "Verificar el nivel de dominio para cookies." },
    ],
    storageKeys: ["_hj*", "hj*"],
    localStorage: ["_hj*"],
    sessionStorage: ["_hj*"],
  },
  clarity: {
    id: "clarity",
    category: "analytics",
    label: "Microsoft Clarity",
    provider: "Microsoft Corporation",
    description: "Grabación de navegación y mapas térmicos de interacción sin datos personales.",
    policyUrl: "https://privacy.microsoft.com/privacystatement",
    cookies: [
      { name: "_clck", duration: "1 año", purpose: "Persistir el ID de usuario Clarity y sus preferencias de página." },
      { name: "_clsk", duration: "24 horas", purpose: "Conectar múltiples visitas de página en una única sesión." },
      { name: "CLID", duration: "1 año", purpose: "Identificador de navegador para Clarity." },
      { name: "MUID", duration: "1 año", purpose: "Identificador de usuario único de Microsoft." },
    ],
    storageKeys: ["_cl*"],
    localStorage: ["_cl*"],
  },
  matomo: {
    id: "matomo",
    category: "analytics",
    label: "Matomo Analytics",
    provider: "InnoCraft Ltd.",
    description: "Plataforma de analítica web local-first y centrada en la privacidad.",
    policyUrl: "https://matomo.org/privacy-policy/",
    cookies: [
      { name: "_pk_id*", duration: "13 meses", purpose: "Almacenar datos de usuario únicos como el ID de visitante." },
      { name: "_pk_ses*", duration: "30 minutos", purpose: "Almacenar datos temporales de la sesión de navegación." },
      { name: "_pk_ref*", duration: "6 meses", purpose: "Almacenar la información de atribución de procedencia." },
    ],
    storageKeys: ["_pk_*"],
    localStorage: ["_pk_*"],
  },
  plausible: {
    id: "plausible",
    category: "analytics",
    label: "Plausible Analytics",
    provider: "Plausible Insights OÜ",
    description: "Analítica web ligera y respetuosa con la privacidad, 100% libre de cookies.",
    policyUrl: "https://plausible.io/data-policy",
    cookies: [],
    storageKeys: [],
  },

  // --- MARKETING & ADVERTISING ---
  meta_pixel: {
    id: "meta_pixel",
    category: "marketing",
    label: "Meta Pixel (Facebook)",
    provider: "Meta Platforms Ireland Ltd.",
    description: "Medición de conversiones, personalización y optimización de campañas publicitarias en Facebook e Instagram.",
    policyUrl: "https://www.facebook.com/privacy/policy",
    cookies: [
      { name: "_fbp", duration: "90 días", purpose: "Almacenar y rastrear visitas en los sitios web para segmentación publicitaria." },
      { name: "_fbc", duration: "90 días", purpose: "Guardar el último clic en un anuncio de Facebook (parámetro fbclid)." },
      { name: "fr", duration: "90 días", purpose: "Cookie de publicidad comportamental de Facebook." },
      { name: "tr", duration: "Sesión", purpose: "Píxel de seguimiento de eventos en tiempo real." },
      { name: "datr", duration: "2 años", purpose: "Identificación del navegador web para seguridad y analítica publicitaria." },
    ],
    storageKeys: ["_fbp*"],
    localStorage: ["_fbp*"],
  },
  facebook_pixel: {
    id: "facebook_pixel",
    category: "marketing",
    label: "Meta Pixel (Facebook)",
    provider: "Meta Platforms Ireland Ltd.",
    description: "Medición de conversiones y retargeting en Meta/Facebook.",
    policyUrl: "https://www.facebook.com/privacy/policy",
    cookies: [
      { name: "_fbp", duration: "90 días", purpose: "Rastreo de conversiones y atribución de campañas." },
      { name: "_fbc", duration: "90 días", purpose: "Identificador de clic de anuncio." },
    ],
    storageKeys: ["_fbp*"],
  },
  google_ads: {
    id: "google_ads",
    category: "marketing",
    label: "Google Ads & Remarketing",
    provider: "Google LLC",
    description: "Medición de conversiones publicitarias y campañas de retargeting de Google Ads.",
    policyUrl: "https://policies.google.com/technologies/ads",
    cookies: [
      { name: "_gcl_au", duration: "90 días", purpose: "Medición de conversiones publicitarias de Google AdSense y Ads." },
      { name: "_gcl_aw", duration: "90 días", purpose: "Conversiones procedentes de clics en anuncios de Google Ads." },
      { name: "IDE", duration: "1 año", purpose: "Publicidad dirigida y medición de rendimiento de DoubleClick." },
      { name: "DSID", duration: "2 semanas", purpose: "Identificar usuario conectado en sitios web ajenos a Google." },
      { name: "RUL", duration: "1 año", purpose: "Audiencias de remarketing de Google Ads." },
    ],
    storageKeys: ["_gcl_*"],
  },
  tiktok_pixel: {
    id: "tiktok_pixel",
    category: "marketing",
    label: "TikTok Pixel",
    provider: "TikTok Technology Limited",
    description: "Medición de rendimiento y segmentación de campañas publicitarias en TikTok.",
    policyUrl: "https://www.tiktok.com/legal/privacy-policy-eea",
    cookies: [
      { name: "_tt_enable_cookie", duration: "13 meses", purpose: "Habilitar la medición de conversiones del píxel de TikTok." },
      { name: "_ttp", duration: "13 meses", purpose: "Medir y mejorar el rendimiento de las campañas publicitarias en TikTok." },
    ],
    storageKeys: ["tt_*", "_ttp*"],
  },
  linkedin_insight: {
    id: "linkedin_insight",
    category: "marketing",
    label: "LinkedIn Insight Tag",
    provider: "LinkedIn Ireland Unlimited Company",
    description: "Informes de conversiones y atribución de campañas profesionales B2B en LinkedIn.",
    policyUrl: "https://www.linkedin.com/legal/privacy-policy",
    cookies: [
      { name: "li_sugr", duration: "90 días", purpose: "Identificador probabilístico de navegador en LinkedIn." },
      { name: "bcookie", duration: "1 año", purpose: "Identificador de sesión de navegador para servicios de LinkedIn." },
      { name: "lidc", duration: "24 horas", purpose: "Enrutamiento de centros de datos para LinkedIn." },
      { name: "UserMatchHistory", duration: "30 días", purpose: "Sincronización de identificadores de publicidad de LinkedIn." },
    ],
  },
  twitter_pixel: {
    id: "twitter_pixel",
    category: "marketing",
    label: "X / Twitter Ads Pixel",
    provider: "X Corp.",
    description: "Medición de conversiones e interacción con campañas publicitarias en X (Twitter).",
    policyUrl: "https://twitter.com/privacy",
    cookies: [
      { name: "personalization_id", duration: "2 años", purpose: "Personalización de publicidad y medición de eventos en X." },
      { name: "muc_ads", duration: "2 años", purpose: "Seguimiento de conversiones publicitarias en X." },
    ],
  },
  hubspot: {
    id: "hubspot",
    category: "marketing",
    label: "HubSpot CRM & Tracking",
    provider: "HubSpot, Inc.",
    description: "Analítica de leads, formularios inteligentes y seguimiento de clientes potenciales.",
    policyUrl: "https://legal.hubspot.com/privacy-policy",
    cookies: [
      { name: "__hstc", duration: "6 meses", purpose: "Rastreo de visitantes únicos, sesiones y marcas de tiempo." },
      { name: "hubspotutk", duration: "6 meses", purpose: "Rastreo de identidad de visitante pasado a formularios." },
      { name: "__hssc", duration: "30 minutos", purpose: "Rastreo de sesiones activas en HubSpot." },
      { name: "__hssrc", duration: "Sesión", purpose: "Determinar si el usuario ha reiniciado su navegador." },
    ],
    storageKeys: ["__hs*", "hubspot*"],
  },

  // --- EMBEDDED MEDIA ---
  youtube: {
    id: "youtube",
    category: "marketing",
    label: "YouTube Video Player",
    provider: "Google LLC",
    description: "Reproducción de contenidos de vídeo integrados y almacenamiento de preferencias del reproductor.",
    policyUrl: "https://policies.google.com/privacy",
    cookies: [
      { name: "VISITOR_INFO1_LIVE", duration: "6 meses", purpose: "Estimar el ancho de banda del usuario en páginas con vídeos de YouTube." },
      { name: "YSC", duration: "Sesión", purpose: "Registrar estadísticas de visualizaciones de vídeo de YouTube." },
      { name: "PREF", duration: "8 meses", purpose: "Almacenar preferencias de configuración del reproductor." },
      { name: "GPS", duration: "30 minutos", purpose: "Rastrear ubicación en dispositivos móviles." },
    ],
    storageKeys: ["yt-*", "yt-remote-*"],
    localStorage: ["yt-*", "yt-remote-*"],
  },
  vimeo: {
    id: "vimeo",
    category: "marketing",
    label: "Vimeo Video Player",
    provider: "Vimeo, Inc.",
    description: "Reproducción de vídeos interactivos alojados en Vimeo y estadísticas de visualización.",
    policyUrl: "https://vimeo.com/privacy",
    cookies: [
      { name: "vuid", duration: "2 años", purpose: "Almacenar el historial de reproducciones de vídeo del usuario en Vimeo." },
      { name: "player", duration: "1 año", purpose: "Guardar las preferencias de volumen y resolución del reproductor." },
    ],
    storageKeys: ["vimeo*"],
  },
  spotify: {
    id: "spotify",
    category: "marketing",
    label: "Spotify Player",
    provider: "Spotify AB",
    description: "Reproducción embebida de canciones, podcasts y listas de reproducción de Spotify.",
    policyUrl: "https://www.spotify.com/legal/privacy-policy/",
    cookies: [
      { name: "sp_t", duration: "1 año", purpose: "Identificador de usuario único de Spotify para contenido embebido." },
      { name: "sp_m", duration: "1 año", purpose: "Preferencias de reproducción y cookies de sesión." },
    ],
  },

  // --- CHAT & CUSTOMER SUPPORT ---
  intercom: {
    id: "intercom",
    category: "marketing",
    label: "Intercom Messenger",
    provider: "Intercom R&D Unlimited Company",
    description: "Widget de mensajería, soporte al cliente en tiempo real y asistencia guiada.",
    policyUrl: "https://www.intercom.com/legal/privacy",
    cookies: [
      { name: "intercom-id-*", duration: "9 meses", purpose: "Identificador anónimo de visitante para conversaciones en Intercom." },
      { name: "intercom-session-*", duration: "7 días", purpose: "Persistir la sesión de chat activa." },
      { name: "intercom-device-id-*", duration: "9 meses", purpose: "Identificador del dispositivo del visitante." },
    ],
    storageKeys: ["intercom*"],
  },
  crisp: {
    id: "crisp",
    category: "marketing",
    label: "Crisp Live Chat",
    provider: "Crisp IM SARL",
    description: "Chat en vivo de soporte y mensajería multicanal para visitantes.",
    policyUrl: "https://crisp.chat/privacy",
    cookies: [
      { name: "crisp-client/*", duration: "6 meses", purpose: "Identificador de sesión de chat en Crisp." },
    ],
    storageKeys: ["crisp-client*"],
  },

  // --- NECESSARY / TECHNICAL / SECURITY ---
  gtm: {
    id: "gtm",
    category: "necessary",
    label: "Google Tag Manager",
    provider: "Google LLC",
    description: "Contenedor técnico para la inyección y gestión centralizada de scripts del sitio web.",
    policyUrl: "https://policies.google.com/privacy",
    cookies: [
      { name: "_gtm_*", duration: "Sesión", purpose: "Depuración técnica de contenedores de Google Tag Manager." },
    ],
  },
  google_recaptcha: {
    id: "google_recaptcha",
    category: "necessary",
    label: "Google reCAPTCHA",
    provider: "Google LLC",
    description: "Protección contra bots automatizados, ataques de fuerza bruta y spam en formularios.",
    policyUrl: "https://policies.google.com/privacy",
    cookies: [
      { name: "_GRECAPTCHA", duration: "6 meses", purpose: "Evaluación de riesgo de bots para protección de formularios." },
      { name: "rc::a", duration: "Persistente", purpose: "Distinguir entre humanos y bots automatizados." },
      { name: "rc::b", duration: "Sesión", purpose: "Distinguir entre humanos y bots automatizados." },
      { name: "rc::c", duration: "Sesión", purpose: "Distinguir entre humanos y bots automatizados." },
    ],
  },
  cloudflare: {
    id: "cloudflare",
    category: "necessary",
    label: "Cloudflare Security & Turnstile",
    provider: "Cloudflare, Inc.",
    description: "Mitigación de ataques DDoS, balanceo de carga CDN y validación de seguridad Turnstile.",
    policyUrl: "https://www.cloudflare.com/privacypolicy/",
    cookies: [
      { name: "__cf_bm", duration: "30 minutos", purpose: "Gestión de bots y mitigación de tráfico malicioso en Cloudflare." },
      { name: "cf_clearance", duration: "1 año", purpose: "Autorización de paso tras superar desafío de seguridad Turnstile/Cloudflare." },
    ],
  },
  stripe: {
    id: "stripe",
    category: "necessary",
    label: "Stripe Payments & Fraud Prevention",
    provider: "Stripe, Inc.",
    description: "Procesamiento seguro de transacciones bancarias, tarjetas y prevención de fraude financiero.",
    policyUrl: "https://stripe.com/privacy",
    cookies: [
      { name: "__stripe_mid", duration: "1 año", purpose: "Prevención de fraude y autenticación de pagos en Stripe." },
      { name: "__stripe_sid", duration: "30 minutos", purpose: "Identificador de sesión de transacción en Stripe." },
      { name: "m", duration: "2 años", purpose: "Detección de fraude financiero en la pasarela de pagos Stripe." },
    ],
    storageKeys: ["__stripe_*"],
    localStorage: ["__stripe_*"],
  },
  paypal: {
    id: "paypal",
    category: "necessary",
    label: "PayPal Checkout",
    provider: "PayPal (Europe) S.à r.l. et Cie, S.C.A.",
    description: "Procesamiento de pagos y pasarela de cobro segura de PayPal.",
    policyUrl: "https://www.paypal.com/webapps/mpp/ua/privacy-full",
    cookies: [
      { name: "ts", duration: "3 años", purpose: "Gestión segura de pagos y prevención de fraude en PayPal." },
      { name: "ts_c", duration: "3 años", purpose: "Autenticación segura de usuario en la pasarela PayPal." },
    ],
  },
};

export type KnownPresetId = keyof typeof SERVICE_PRESETS | string;
